services:
  app:
    image: ghcr.io/lunarcatowo/embed-service:main
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - API_KEY=${API_KEY}
      - YOUTUBE_CHANNEL_ID=${YOUTUBE_CHANNEL_ID}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${PORT:-3000}/app/json/featured-video"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=embed-service"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --rolling-restart --scope embed-service --label-enable
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=60